#!/bin/sh

cat <<EOF
=====================================================================
Este servidor se encuentra en la Antártida y como usted no se encuen-
tra allí, no tiene manera de acceder al teclado físico del equipo.

Pero puede acceder en forma remota mediante protocolo telnet.
Utilice el nombre de usuario 'root' y la clave 'ultrasecreta'.
=====================================================================
EOF
read KEY
